version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # <- Alterado aqui
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    ports:
      - '9092:9092'
    networks:
      - kafka-network

  kafka-init:
    image: apache/kafka:latest
    depends_on:
      - kafka
    entrypoint: >
      /bin/sh -c " echo 'Aguardando Kafka...'; while ! nc -z kafka 9092; do
        sleep 1;
      done; echo 'Kafka está pronto! Criando tópico...'; /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic image-topic; echo 'Tópico criado com sucesso!'; "
    networks:
      - kafka-network

  api:
    build: .
    container_name: flask-api
    depends_on:
      - kafka-init
    ports:
      - '5000:5000'
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
