apiVersion: v1
kind: Service
metadata:
  name: radiology-ia-model-service
spec:
  selector:
    app: radiology-ia-model
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer  # ou "ClusterIP" se for apenas interno