apiVersion: apps/v1
kind: Deployment
metadata:
  name: radiology-ia-model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: radiology-ia-model
  template:
    metadata:
      labels:
        app: radiology-ia-model
    spec:
      containers:
        - name: radiology-ia-model
          image: radiology-ia-model:v1
          ports:
            - containerPort: 5000